# FILEPATHS
watershed_gis_polygon: '${DATA_DIR}/shp_watershed/norfolk_wshed_epsg32147_state_plane_m.shp'
system_directory: '${PACKAGE_DIR}/system'
DEM_fullres: '${DATA_DIR}/fullres_dem_m.tif'
landuse_lookup_file: '${DATA_DIR}/landuse_lookup_tables.csv'
landuse_raster: '${DATA_DIR}/landuse_clipped_to_triton_extent.tif'
TRITONSWMM_software_directory: '${PACKAGE_DIR}/triton'
TRITONSWMM_git_URL: 'https://code.ornl.gov/hydro/triton.git'
TRITONSWMM_branch_key: '84c367f727946be38df2ec3383a1a2a9adfa7780' # '4119d51d7e6a9e410859a37fce1631e20de931f3' # 'c7288a354c9a042fe441d8d9f0216415e1576c32' # 'be56b7c0f2816a0bd7bc99ae42b290f3b993c066' 
TRITON_machine_bash_script: 'default_OPENMP.sh'
TRITON_machine_name: 'Linux'
# TRITON_SWMM_software_compilation_script: '${PACKAGE_DIR}/template_compile_triton_swmm.sh'
triton_swmm_configuration_template: '${DATA_DIR}/TRITON_SWMM_definition_template.cfg'
SWMM_hydraulics: '${DATA_DIR}/swmm/hague_hydraulics_model_template.inp'
SWMM_hydrology: '${DATA_DIR}/swmm/hague_hydrology_model_template.inp'
SWMM_full: '${DATA_DIR}/swmm/hague_full_model_template.inp'
subcatchment_raingage_mapping: '${DATA_DIR}/b_sub_ids_and_mrms_rain_col.csv'
subcatchment_raingage_mapping_gage_id_colname: 'raingage_id'
# ATTRIBUTE NAMES
landuse_description_colname: 'original_description'
landuse_lookup_class_id_colname: 'CLASS_ID'
landuse_lookup_mannings_colname: 'mannings'
landuse_plot_color_colname: 'plot_color'
# TOGGLES
toggle_use_swmm_for_hydrology: True
toggle_use_constant_mannings: False
toggle_full_swmm_model: True
# CONSTANTS
dem_outside_watershed_height: 9999 # meters
dem_building_height: 80 # meters
# PARAMETERS
target_dem_resolution: 3.5 # meters

# TODO
# - use an actually unprocessed DEM with a 'bathtub' shapefile that contains the watershed
#   and any connections to the variable boundary condition as well as a building shapefile to create the processed DEM