analysis_id: 'single_sim' # analysis folder name; will be created if it doesn't exist
weather_event_indices: ['year', 'event_type', 'event_id']
weather_time_series_storm_tide_datavar: 'waterlevel_m'
weather_time_series_timestep_dimension_name: 'timestep'
weather_timeseries: '${DATA_DIR}/obs_event_tseries_from_yrs_with_complete_coverage.nc'
weather_event_summary_csv: '${DATA_DIR}/obs_event_summaries_from_yrs_with_complete_coverage.csv'
storm_tide_boundary_line_gis: '${DATA_DIR}/shp_boundary_condition/variable_bc.shp'
weather_events_to_simulate: '${DATA_DIR}/hurricane_irene_event_index.csv'
analysis_description: 'Single Simulation of Hurricane Irene 8-27-2011'
TRITON_SWMM_make_command: 'hpc_swmm_omp'
run_mode: "serial"
# UNITS
rainfall_units: 'mm/hr'
storm_tide_units: 'm'
# TOGGLES
toggle_benchmarking_analysis: False
toggle_storm_tide_boundary: True
# PARAMETERS
TRITON_processed_output_type: 'zarr' # zarr or nc
TRITON_raw_output_type: 'bin' # bin or asc
manhole_diameter: 1.2
manhole_loss_coefficient: 0.1
hydraulic_timestep_s: 0.01
TRITON_reporting_timestep_s: 120
open_boundaries: 1