use-conda: false
conda-frontend: mamba
executor: slurm
jobs: 100
default-resources:
  slurm_partition: "standard-mem"
  slurm_account: "quinnlab"
  runtime: 60
  mem_mb: 4000
printshellcmds: true
rerun-incomplete: true
