variable_boundary_condition: "{DATA_DIR}/variable_bc.shp"
watershed_shapefile: "{DATA_DIR}/norfolk_wshed_epsg32147_state_plane_m.shp"
mannings_file: "{DATA}/mannings_norfolk_4.dem"
DEM_processed: "{DATA}/norfolk_4.dem"
DEM_fullres: "{DATA}/fullres_dem_m.tif"
landuse_lookup: "{DATA}/landuse_lookup_tables.xlsx"
SWMM_hydraulics: "{DATA}/hague_hydraulics_model_template.inp"
SWMM_hydrology: "{DATA}/hague_hydrology_model_template.inp"
SWMM_full: "{DATA}/hague_full_model_template.inp"
landuse_raster: "{DATA}/landuse_clipped_to_triton_extent.tif"
TRITONSWMM_software_directory: "{DATA}/software"
weather_timeseries: "{DATA}/obs_event_tseries_from_yrs_with_complete_coverage.nc"
weather_event_summary_csv: "{DATA}/obs_event_summaries_from_yrs_with_complete_coverage.csv"
subcatchment_raingage_mapping: "{DATA}/b_sub_ids_and_mrms_rain_col.csv"