analysis_id: 'norfolk_irene_benchmarking'
benchmarking_analysis: '{DATA}/benchmarking_analysis.xlsx'
weather_event_indexers: {'year':9, 'event_type':'compound', 'event_id':1}
event_description: 'Hurricane Irene 8-27-2011'
analysis_folder: '{DATA}/benchmarking_analysis'
TRITONSWMM_software_compilation_script: '${PACKAGE_DIR}/compile_tritonswmm_wsl.sh'
toggle_benchmarking_analysis: True